# SEO settings
title: "cryp7.net"
#title2: "space" # default: ""
description: "Just this site ya know"
keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace, cryp7, cryp7.net, range.cryp7.net, enkaskal"
url: https://cryp7.net
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

#google_analytics: UA-XXXXX-XX
repo: http://github.com/enkaskal/enkaskal.github.io
#disqus_shortname: "hnbloggithub"
twitter_username: "enkaskal"
github_username: "enkaskal"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Stefan Schwoegler"
  job      : "Just this guy ya know!"
  bio      : "I've done some stuff...google me ;P"
  thumb    : https://www.gravatar.com/avatar/daa3ff28e9dc091bf850c0bba8182197
  email    : enkaskal@cryp7.net
  url      : https://cryp7.net
  github   : https://github.com/enkaskal
  twitter  : https://twitter.com/enkaskal
#  facebook : https://www.facebook.com/heiswayi.nrird
#  linkedin : http://linkedin.com/in/nrird

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@enkaskal"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
